name: Django Backend Test and Build-Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python3
        uses: actions/setup-python @v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install Python Package
        run: |
          sudo pip install poetry
          cd backend
          poetry install

      # packageをキャッシュしたほうがいいかも

      - name: DB Migrations
        run: |
          cd backend
          poetry run python3 manage.py makemigrations
          poetry run python3 manage.py migrate

      - name: Run Tests
        run: |
          cd backend
          poetry run python3 manage.py test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "hello"
        # DjangoをECR/ECSへデプロイ
        # NginxをECR/ECSへデプロイ
        # VueをS3へデプロイ
