name: doboku-post

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "hello"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "hello"
